# https://kubernetes.io/docs/admin/extensible-admission-controllers/

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: denyimages
webhooks:
  - name: denyimages.stevesloka.com
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    failurePolicy: Fail
    clientConfig:
      url: "https://foo.com"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRRDdlL3lVbG43UzJUQU5CZ2txaGtpRzl3MEJBUXNGQURBWE1SVXdFd1lEVlFRRERBeGgKWkcxcGMzTnBiMjVmWTJFd0lCY05NVGd3TlRFNU1ERXdOVEl6V2hnUE1qSTVNakF6TURNd01UQTFNak5hTUJjeApGVEFUQmdOVkJBTU1ER0ZrYldsemMybHZibDlqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU9Tbi9vRXY0aWF3aDZLL1VFTDFwclBGRVNaSTZuNHdpNUN0aFpDMk5pWk0xUUtvWUtXN2JDMTgKc3grNnVVOWIrQVFTYlRNOVZmLzNINU5iUThUYmdYdmlGWWNKSm1pRXVLRlhQY2xibGJ3UTc2dmE2ZGNyT0NUcAo1L3ljYnhjeWNIazhBclpxQkxRVkdnbTNkdjBEOWR6UXoyV2RxZzdVNkNvamZDWHhsQjBqR09XL3RhaE9ucWdzCnB4OWwxa2xGakd4YmVERnRWd0FNY1VjMlI5VFAvTmNrN1ZYYzcxOWpsK1paQUJhYW5ubW80ZUczUm1tVm92UTAKK3AwT3FidGdkTVd4akpPL2xid2JsQnZSdXZtYTdydHdxV1JXN3dHaUh4L0prcWNVdUNYNUFraHFTbGNpb3FpVwplcnNiS3lJYm1leElwdWo5VkRYTHI3ZXVTS2dHUWRVQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCkE3TUd1QUxCNzNQam9VMEJVL1psejBIcTZYZm5xRDVoc3BNQ3Z3QjZkb2YvZUdXYk9GOUxxK1d3YmcrY2d6Z1YKd0s0bjhOT0hHT3RsamRTa3VubUNuTU5VQWxjYk1SdSs0NHRxeXUyMFp6YnZMS2lJV1kvNGpja2lkZ1VqRndyYwo0YW42OE5KcmQyRm1vSVhrMnBsKzFqQ0ppTFo0Uzc0dzJPd25hb2RseEx3VDFBSlNMN0lZOHkrbmN0eHFiek82CkQ3R0tPVjVWTU41SUdGbEcvV3hxREUzaHQ1NEtxWmFaeG9NdVNKNm1NTkhuR2daaFdINy9nb010VHAzeDgxeWIKRzFaWnh3MlhqUjF4azBQME44WnRyT3ZBdXptRFcyMTNuR1llTW52L3FJM3l3QUNnY3kzcjc1UXp2NENzUFBRYQpCbTlWT2ZvZlB1YXpOZWhtWTdOdkZnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=